### ISSUE TITLE
Create Ui for Rock Paper scissors

### ISSUE THREAD

**Issue by Hoshitarou** [BSIT32E3-GROUP-FOUR/Rock-paper-scissors-Group4#1]

**Comment by Hoshitarou** [comment]
https://github.com/BSIT32E3-GROUP-FOUR/Rock-paper-scissors-Group4/pull/4

**Comment by Angeles-Aaron-BSIT32E3** [comment]
https://github.com/BSIT32E3-GROUP-FOUR/Rock-paper-scissors-Group4/compare/RockPaperScissorMVC?expand=1

**Comment by Hoshitarou** [comment]
https://github.com/BSIT32E3-GROUP-FOUR/Rock-paper-scissors-Group4/pull/5
